name: zig

on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install Zig
      uses: jetsung/install-zig@v0.0.3
      with:
        version: 0.15.1
    - name: Build
      run: zig build --release=fast
